import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // Documentation sidebar with organized structure
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Getting Started',
      items: [
        'intro',
        'installation',
      ],
    },
    {
      type: 'category',
      label: 'Setup & Configuration',
      items: [
        'configuration',
      ],
    },
    {
      type: 'category',
      label: 'Development',
      items: [
        'development',
      ],
    },
  ],

  // By default, Docusaurus generates a sidebar from the docs folder structure
  // Uncomment the line below to use auto-generation instead
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
